#!/bin/bash
echo "Setup vim"
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone https://github.com/sbashar/script.git ~/script
ln ~/script/.vimrc .vimrc
vim +PluginInstall +qall
echo done
